version: '3'
services:
  todo_db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
